// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1eL_spHaTr3vnmi5bDtR4guPyU7ngFQc',
    appId: '1:513210799137:web:835e7b14a86c2e3d0ebf60',
    messagingSenderId: '513210799137',
    projectId: 'instachat-60cfb',
    authDomain: 'instachat-60cfb.firebaseapp.com',
    storageBucket: 'instachat-60cfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOvrLAlcozjK5C-7i8kaFhji9N3FNj0bU',
    appId: '1:513210799137:android:f71c6a8507b80e960ebf60',
    messagingSenderId: '513210799137',
    projectId: 'instachat-60cfb',
    storageBucket: 'instachat-60cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC6qnzReRrww-55EsBCzeZqeZlqMPXNPo',
    appId: '1:513210799137:ios:73cf1bb912fc270e0ebf60',
    messagingSenderId: '513210799137',
    projectId: 'instachat-60cfb',
    storageBucket: 'instachat-60cfb.appspot.com',
    androidClientId: '513210799137-088cnp7d8jftjbr43an10afcu9e3oh7a.apps.googleusercontent.com',
    iosClientId: '513210799137-n9l1mf94r03233o9akanli852avhb5ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication55',
  );

}